# Generated by Django 2.1.1 on 2019-10-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20191008_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('questionNumber', models.IntegerField()),
                ('quesitonText', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='reviewers',
            fields=[
                ('reviewerId', models.AutoField(primary_key=True, serialize=False)),
                ('reviewerTitle', models.CharField(max_length=100)),
                ('reviewerContent', models.CharField(max_length=9999)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewerSubject', to='registration.subject')),
            ],
        ),
        migrations.CreateModel(
            name='sampleQuizzes',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('quizTitle', models.CharField(max_length=100)),
                ('numberOfItems', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizSubject', to='registration.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='registration.sampleQuizzes'),
        ),
    ]
