# Generated by Django 2.1.1 on 2019-10-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20191008_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewers',
            name='reviewerContent',
        ),
        migrations.AddField(
            model_name='reviewers',
            name='reviewerFile',
            field=models.FileField(null=True, upload_to='Desktop/'),
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
