# Generated by Django 2.1.1 on 2019-10-08 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20191008_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewers',
            name='reviewerContent',
            field=models.CharField(default='asdasdas', max_length=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
