# Generated by Django 2.1.1 on 2019-10-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20191008_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewers',
            name='reviewerFile',
            field=models.FileField(blank=True, upload_to='Desktop/'),
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
