# Generated by Django 2.1.1 on 2019-11-14 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20191008_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='choiceA',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='choiceB',
            field=models.CharField(default='b', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='choiceC',
            field=models.CharField(default='c', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='choiceD',
            field=models.CharField(default='d', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='questionType',
            field=models.CharField(default='asdfg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='classCode',
            field=models.CharField(default='abcdef', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
