# Generated by Django 2.1.1 on 2019-11-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20191114_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplequizzes',
            name='subject',
        ),
        migrations.AddField(
            model_name='samplequizzes',
            name='reviewer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewerQuiz', to='registration.reviewers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
