# Generated by Django 2.1.1 on 2019-11-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20191114_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='quesitonText',
            new_name='questionText',
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
