# Generated by Django 2.1.1 on 2019-11-14 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20191114_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplequizzes',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
        migrations.RemoveField(
            model_name='samplequizzes',
            name='numberOfItems',
        ),
        migrations.AlterField(
            model_name='studentspersubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
